import { pgTable, uuid, varchar, text, integer, boolean, jsonb, timestamp } from "drizzle-orm/pg-core";
export const listedProperties = pgTable("listed_properties", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  description: text("description"),
  barcode: varchar("barcode", { length: 50 }),
  price: integer("price").default(0),
  priceDisplay: varchar("price_display", { length: 100 }),
  location: varchar("location", { length: 255 }),
  propertyType: varchar("property_type", { length: 100 }),
  status: varchar("status", { length: 50 }).default("draft"),
  bedrooms: integer("bedrooms").default(0),
  bathrooms: integer("bathrooms").default(0),
  areaSqft: integer("area_sqft").default(0),
  parking: integer("parking").default(0),
  featured: boolean("featured").default(false),
  images: jsonb("images").default([]),
  amenities: jsonb("amenities").default([]),
  metaTitle: varchar("meta_title"),
  metaDescription: text("meta_description"),
  focusKeywords: varchar("focus_keywords"),
  faqs: jsonb("faqs").default([]),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
export const blogPosts = pgTable("blog_posts", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  excerpt: text("excerpt"),
  content: text("content"),
  category: varchar("category", { length: 100 }),
  authorName: varchar("author_name", { length: 255 }),
  status: varchar("status", { length: 50 }).default("draft"),
  featuredImage: text("featured_image"),
  metaTitle: varchar("meta_title"),
  metaDescription: text("meta_description"),
  focusKeyword: varchar("focus_keyword"),
  tags: jsonb("tags").default([]),
  faqs: jsonb("faqs").default([]),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
export const communities = pgTable("communities", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  description: text("description"),
  shortDescription: text("short_description"),
  image: text("image"),
  gallery: jsonb("gallery").default([]),
  location: varchar("location", { length: 255 }),
  avgPrice: varchar("avg_price", { length: 100 }),
  propertyTypes: jsonb("property_types").default([]),
  amenities: jsonb("amenities").default([]),
  metaTitle: varchar("meta_title"),
  metaDescription: text("meta_description"),
  status: varchar("status", { length: 50 }).default("draft"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
export const downloadRequests = pgTable("download_requests", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: varchar("name", { length: 255 }),
  email: varchar("email", { length: 255 }),
  phone: varchar("phone", { length: 50 }),
  type: varchar("type", { length: 50 }),
  propertyId: uuid("property_id"),
  propertyTitle: varchar("property_title", { length: 255 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});
